config/routes.rb
TimesheetManagement::Application.routes.draw do

  authenticated :user do
    root :to => 'home#index', :as => :authenticated_root
  end
   
  devise_for :users, :controllers => {:confirmations => 'confirmations'}, :skip => [:sessions]
  devise_scope :user do 
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'login' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'forgot-password' => 'devise/passwords#new', :as => :new_user_password
    get 'confirmation-instruction' => 'confirmations#new', :as => :new_user_confirmation
    put "/confirm" => "confirmations#confirm"
  end
  
  devise_scope :user do 
    put "/confirm" => "confirmations#confirm"
  end
  
  resources :employees, except: ["show"]
  resources :clients
  resources :projects, except: ["show"]
  resources :activity_types, except: ["show"]
  resources :tasksheets 
  get "/projects_for_client" => "tasksheets#projects_for_client"
  
  post "tasksheets/create_row" => "tasksheets#create_row", as: "create_row"

  resources :reports 
  get "/project_for_client" => "reports#project_for_client"
  post "reports/submit_for_approval" => "reports#submit_for_approval", as: "submit_for_approval"
  post "reports/all_submit" => "reports#all_submit", as: "all_submit"
  
  resources :check_reports
  get "/project_for_client_admin" => "check_reports#project_for_client_admin"
  post "check_reports/accept_data" => "check_reports#accept_data", as: "accept_data"
  post "check_reports/reject_data" => "check_reports#reject_data", as: "reject_data"
  post "check_reports/reason_for_rejection" => "check_reports#reason_for_rejection", as: "reason_for_rejection"
  post "check_reports/accept_all_data" => "check_reports#accept_all_data", as: "accept_all_data"
  post "check_reports/reject_all_data" => "check_reports#reject_all_data", as: "reject_all_data"
  

   root :to => 'home#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  ############
  ## Requires
  ############
  #############
  ## Constants
  #############
  ################
  ## Associations
  ################
  has_one :user 
  
  ##############
  ## Call Backs
  ##############
  before_validation :squish_fields
  accepts_nested_attributes_for :user

  #######################
  ## Attribute Accessors
  #######################
  attr_accessible :firstname, :lastname, :code, :user_attributes

  ###############
  ## Validations
  ###############
  validates :firstname, presence: true, uniqueness: { case_sensitive: false} ,
                       format: { with: /^[a-zA-Z\s]*$/, message: "must be character and space" }

  validates :lastname, presence: true, uniqueness: { case_sensitive: false} ,
                       format: { with: /^[a-zA-Z\s]*$/, message: "must be character and space" }

  validates :code, presence: true, uniqueness: { case_sensitive: false} ,
                   format: { with: /^[a-zA-Z0-9]*$/, message: "must be alphanumeric" }

  #################
  ## Class Methods
  #################
  class << self
  end

  ######################
  ## Virtual Attributes
  ######################
  ######################
  ## Public Methods
  #####################
  def self.getemployee
    Employee.all
  end
  
  #####################
  ## Protected Methods
  #####################
  protected

  #####################
  ## Private Methods
  #####################
  private
    def squish_fields
      self.firstname = ((self.firstname.present?) ? self.firstname.squish : nil)
      self.lastname = ((self.lastname.present?) ? self.lastname.squish : nil)
      self.code = ((self.code.present?) ? self.code.squish : nil)
    end

end  

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  ###########
  ## Filters
  ###########
  ############
  ## Requires
  ############
  #############
  ## Constants
  #############
  ##################
  ## Public Actions
  ##################

  #show the list of employees
  def index
    @employees = Employee.all
  end

  #blank object to show the form to get the new employee
  def new
    @employee = Employee.new
    #build user in employee object
    @employee.build_user
  end

  #actually create the new employee
  def create
    #create the object of employee and assign the attributes in the request
    @employee = Employee.new(params[:employee])
    @employee.build_user(params[:employee][:user_attributes])
    #save the employee
    if @employee.save
      #if saved, redirect to employee index page with success message
      return redirect_to employees_path, notice: "employee created successfuly"
    else
      #if saved, render the form with error messages
      return render action: "new"
    end
  end

  #edit the existing data
  def edit
    #find the employee from the Model: Employee where id of the employee is equal id in the params and assign it to variable “@employee”
    @employee = Employee.where(id: params[:id]).first
    #if @employee is blank
    if @employee.blank?
      #then redirect to employee index page with error message
      return redirect_to employees_path, error: "Specified employee is not found"
    end
  end
  
  #update the existing data
  def update
    #find the employee from the Model: Employee where id of the employee is equal id in the params and assign it to variable “@employee”
    @employee = Employee.where(id: params[:id]).first
    if @employee.blank?
    #if @employee is blank
      return redirect_to employees_path, error: "Specified employee is not found"
      #then redirect to employee index page with error message
    end
    #If the record is updated successfully except "email", then 
    if @employee.update_attributes(params[:employee].except("email"))
      #return and redirect to “employees index” page success message
      return redirect_to employees_path, notice: "employee updated successfully"
    #else  
    else
      #return and render the edit action of employee
      return render action: "edit"
    end
  end

  #destroy the employee and associated user
  def destroy
    #find the employee from the Model: Employee where id of the employee is equal id in the params and assign it to variable “@employee”
    @employee = Employee.where(id: params[:id]).first
    #@user = User.where(employee_id: params[:id]).first
    #if @employee is blank then
    if @employee.blank?
      #return and redirect to "employees index" page with error message 
      return redirect_to employees_path, error: "Specified employee is not found"
    end    
    #call the "destroy" method with object, if object is successfully deleted
    if @employee.destroy && @employee.user.destroy
      #redirect to "employees index" page with an success message
      return redirect_to employees_path, notice: "employee destroyed successfully"
    #else  
    else
      #redirect to "employees index" page with an success message
      return redirect_to employees_path, notice: "employee could not destroyed"
    end
  end

  #####################
  ## Protected Methods
  #####################
  protected

  ###################
  ## Private Methods
  ###################
  private
  
end               

app/views/employees/_employee.html.erb
<tr>
  <td><%= employee.firstname %> </td>
  <td><%= employee.lastname %> </td>
  <td><%= employee.code %> </td>
  <td><%= employee.user.name %> </td>
  <td><%= employee.user.email %> </td>
  <td>
    <%= link_to("Edit", edit_employee_path(employee.id)) %>
    &nbsp;|&nbsp;
    <%= link_to("Delete", employee, confirm: 'Are you sure?', method: :delete) %>
  </td>
</tr>
 

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <table class="imagetable">
    <tr>
      <td>
        <%= f.label :firstname %>
      </td>
      <td>
        <%= f.text_field :firstname %>&nbsp;
        <% if @employee.errors.present? && @employee.errors[:firstname].present? %>
          <%= @employee.errors[:firstname].join(", ") %>
        <% end %>
      </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr>
      <td>
        <%= f.label :lastname %>
      </td>
      <td>
        <%= f.text_field :lastname %>&nbsp;
        <% if @employee.errors.present? && @employee.errors[:lastname].present? %>
          <%= @employee.errors[:lastname].join(", ") %>
        <% end %>
      </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr>
      <td>
        <%= f.label :code %>
      </td>
      <td>
        <%= f.text_field :code %>&nbsp;
        <% if @employee.errors.present? && @employee.errors[:code].present? %>
          <%= @employee.errors[:code].join(", ") %>
        <% end %>
      </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>
    <% flag = false %>
    <% if params[:action] == "edit" || params[:action] == "update" %>
      <% flag = true %>
    <% end %>    
    <%= f.fields_for :user  do |user_fields| %>
      <tr>
        <td>
          <%= user_fields.label :name %>
        </td>
        <td>
          <%= user_fields.text_field :name %>&nbsp;
          <% if @employee.user.errors.present? && @employee.user.errors[:name].present? %>
            <%= @employee.user.errors[:name].join(", ") %>
          <% end %>
        </td>
      </tr>
      <tr><td colspan="2">&nbsp;</td></tr>
      <tr>
        <td>
          <%= user_fields.label :email %>
        </td>
        <td>
          <%= user_fields.text_field :email, :readonly => flag %>&nbsp;
          <% if @employee.user.errors.present? && @employee.user.errors[:email].present? %>
            <%= @employee.user.errors[:email].join(", ") %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td colspan="5">
        <%= f.submit %>
      </td>
    </tr>
  </table>
<% end %>  

app/views/employees/edit.html.erb
<h1> Edit the employee </h1>
<%= render "employees/form" %>
<%= link_to("Back", employees_path) %>

app/views/employees/index.html.erb
<h1> Employees Management </h1>
<div>
  <table class="imagetable">
    <tr>
      <th align = "left"> First Name </td>
      <th align = "left"> Last Name </td>
      <th align = "left"> Employee Code </td>
      <th align = "left"> User Name </td>
      <th align = "left"> Email </td>
      <th colspan="2", align = "left"> Actions </td>
    </tr>
    <% if @employees.present? %>
      <%= render partial: "employees/employee", collection: @employees %>
    <% else %>
      <tr><td colspan="4"> "No employee found" </td></tr>
    <% end %> 
  </table>
  <%= link_to("New Employee", new_employee_path) %><br />
</div>

app/views/employees/new.html.erb
<h1> Add new Employee </h1>
<%= render "employees/form" %>
<%= link_to("back", employees_path) %> 