config/routes.rb
TimesheetManagement::Application.routes.draw do

  authenticated :user do
    root :to => 'home#index', :as => :authenticated_root
  end
   
  devise_for :users, :controllers => {:confirmations => 'confirmations'}, :skip => [:sessions]
  devise_scope :user do 
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'login' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'forgot-password' => 'devise/passwords#new', :as => :new_user_password
    get 'confirmation-instruction' => 'confirmations#new', :as => :new_user_confirmation
    put "/confirm" => "confirmations#confirm"
  end
  
  devise_scope :user do 
    put "/confirm" => "confirmations#confirm"
  end
  
  resources :employees, except: ["show"]
  resources :clients
  resources :projects, except: ["show"]
  resources :activity_types, except: ["show"]
  resources :tasksheets 
  get "/projects_for_client" => "tasksheets#projects_for_client"
  
  post "tasksheets/create_row" => "tasksheets#create_row", as: "create_row"

  resources :reports 
  get "/project_for_client" => "reports#project_for_client"
  post "reports/submit_for_approval" => "reports#submit_for_approval", as: "submit_for_approval"
  post "reports/all_submit" => "reports#all_submit", as: "all_submit"
  
  resources :check_reports
  get "/project_for_client_admin" => "check_reports#project_for_client_admin"
  post "check_reports/accept_data" => "check_reports#accept_data", as: "accept_data"
  post "check_reports/reject_data" => "check_reports#reject_data", as: "reject_data"
  post "check_reports/reason_for_rejection" => "check_reports#reason_for_rejection", as: "reason_for_rejection"
  post "check_reports/accept_all_data" => "check_reports#accept_all_data", as: "accept_all_data"
  post "check_reports/reject_all_data" => "check_reports#reject_all_data", as: "reject_all_data"
  

   root :to => 'home#index'

end

app/controllers/activity_types_controller.rb
class ActivityTypesController < ApplicationController
  ###########
  ## Filters
  ###########
  ############
  ## Requires
  ############
  #############
  ## Constants
  #############
  ##################
  ## Public Actions
  ##################

  #show the list of Activity Type
  def index
    @activity_types = ActivityType.all
  end
  
  #blank object to show the form to get the new Activity Type
  def new
    @activity_type = ActivityType.new
  end
  
  #actually create the new Activity Type
  def create
    #create the object of Activity Type and assign the attributes in the request
    @activity_type = ActivityType.new(params[:activity_type])
    #save the activity_type
    if @activity_type.save
      #if saved, redirect to "Activity Type List" page with success message
      return redirect_to activity_types_path, notice: "Activity Type created successfuly"
    else
      #if saved, render the form with error messages
      return render action: "new"
    end    
  end
  
  #edit the existing data 
  def edit
    #find the activity type from the Model: ActivityType where id of the activity type is equal id in the params and assign it to variable “@activity_type”
    @activity_type = ActivityType.where(id: params[:id]).first
    #if @activity_type is blank 
    if @activity_type.blank?
      #redirect to Activity Type list page with an error message
      return redirect_to activity_types_path, error: "Specified Activity Type is not found"
    end
  end
  
  #update the existing data
  def update
  #debugger
    #find the activity type from the Model: ActivityType where id of the activity type is equal id in the params and assign it to variable “@activity_type”
    @activity_type = ActivityType.where(id: params[:id]).first
    #if @activity_type is blank
    if @activity_type.blank?
      #redirect to Activity Type list page with an error message
      return redirect_to activity_types_path, error: "Specified Activity Type is not found"
    end
    #if update is saved successfully
    if @activity_type.update_attributes(params[:activity_type])
      #redirect to Activity Type list page with success message
      return redirect_to activity_types_path, notice: "Activity Type updated successfully"
    #else 
    else
      #return and render the action "edit"
      return render action: "edit"
    end
  end
  
  #destroy the activity type
  def destroy
    #find the activity_type from the Model: ActivityType where id of the activity type is equal id in the params and assign it to variable “@activity_type”
    @activity_type = ActivityType.where(id: params[:id]).first
    #if @activity_type is blank
    if @activity_type.blank?
      #redirect to Activity Type list page with an error message
      return redirect_to activity_types_path, error: "Specified Activity Type is not found"
    end
    #call the "destroy" method with object, if object is successfully deleted 
    if @activity_type.destroy
      #redirect to Activity Type list page with an success message
      return redirect_to activity_types_path, notice: "Activity Type destroyed successfully"
    #else  
    else
      #return and redirect to Activity Type list page with an success message
      return redirect_to activity_types_path, notice: "Activity Type could not destroyed" 
    end
  end

  #####################
  ## Protected Methods
  #####################
  protected

  ###################
  ## Private Methods
  ###################
  private

end               
  
  
  

app/views/activity_types/_activity_type.html.erb
<tr>
  <td><%= activity_type.name %> </td>
  <td>
    <%= link_to("Edit", edit_activity_type_path(activity_type.id)) %>
    &nbsp;|&nbsp;
    <%= link_to("Delete", activity_type, confirm: 'Are you sure?', method: :delete) %>
  </td>
</tr>
 

app/views/activity_types/_form.html.erb
<%= form_for(@activity_type) do |f| %>
  <div>
    <table class="imagetable">
      <tr>
        <td>
          <%= f.label :name %>
        </td>
        <td>
          <%= f.text_field :name %>&nbsp;
          <% if @activity_type.errors.present? && @activity_type.errors[:name].present? %>
            <%= @activity_type.errors[:name].join(", ") %>
          <% end %>
        </td>
      </tr>
      <tr><td colspan="2">&nbsp;</td></tr>
      <tr>
        <td colspan="2">
          <%= f.submit %>
        </td>
      </tr>
    </table>
  </div>
<% end %>  

app/views/activity_types/edit.html.erb
<h1> Edit the activity type </h1>
<%= render "activity_types/form" %>
<%= link_to("Back", activity_types_path) %>

app/views/activity_types/index.html.erb
<h1> Activity Types Management </h1>
<div>
  <table class="imagetable">
    <tr>
      <th align = "left">  Name </td>
      <th align = "left"> Actions </td>
    </tr>
    <% if @activity_types.present? %>
      <%= render partial: "activity_types/activity_type", collection: @activity_types %>
    <% else %>
      <tr><td colspan="2"> "No activity type found" </td></tr>
    <% end %>
  </table>
  <%= link_to("New Activity Type", new_activity_type_path) %><br />
</div>

app/views/activity_types/new.html.erb
<h1> Add new Activity Type </h1>
<%= render "activity_types/form" %>
<%= link_to("back", activity_types_path) %> 