config/routes.rb
TimesheetManagement::Application.routes.draw do

  authenticated :user do
    root :to => 'home#index', :as => :authenticated_root
  end
   
  devise_for :users, :controllers => {:confirmations => 'confirmations'}, :skip => [:sessions]
  devise_scope :user do 
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'login' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'forgot-password' => 'devise/passwords#new', :as => :new_user_password
    get 'confirmation-instruction' => 'confirmations#new', :as => :new_user_confirmation
    put "/confirm" => "confirmations#confirm"
  end
  
  devise_scope :user do 
    put "/confirm" => "confirmations#confirm"
  end
  
  resources :employees, except: ["show"]
  resources :clients
  resources :projects, except: ["show"]
  resources :activity_types, except: ["show"]
  resources :tasksheets 
  get "/projects_for_client" => "tasksheets#projects_for_client"
  
  post "tasksheets/create_row" => "tasksheets#create_row", as: "create_row"

  resources :reports 
  get "/project_for_client" => "reports#project_for_client"
  post "reports/submit_for_approval" => "reports#submit_for_approval", as: "submit_for_approval"
  post "reports/all_submit" => "reports#all_submit", as: "all_submit"
  
  resources :check_reports
  get "/project_for_client_admin" => "check_reports#project_for_client_admin"
  post "check_reports/accept_data" => "check_reports#accept_data", as: "accept_data"
  post "check_reports/reject_data" => "check_reports#reject_data", as: "reject_data"
  post "check_reports/reason_for_rejection" => "check_reports#reason_for_rejection", as: "reason_for_rejection"
  post "check_reports/accept_all_data" => "check_reports#accept_all_data", as: "accept_all_data"
  post "check_reports/reject_all_data" => "check_reports#reject_all_data", as: "reject_all_data"
  

   root :to => 'home#index'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  ###########
  ## Filters
  ###########
  ############
  ## Requires
  ############
  #############
  ## Constants
  #############
  ##################
  ## Public Actions
  ##################

  #show the reports based on the data in tasksheets
  def index
    #if from date is present then
    if params[:from].present?
      #debugger
      #concate of year, month and day into single date 
      from = params[:from]["year"] +'/'+params[:from]["month"] +'/'+ params[:from]["day"]
      #concate of year, month and day into single date 
      to = params[:to]["year"] +'/'+params[:to]["month"] +'/'+ params[:to]["day"]
      #define a hash
      hash = {} 
      #check if client is present then
      if params[:client].present?
        #put the client into hash
        hash[:client_id] = params[:client]
      end 
      #check if project is present then 
      if params[:project].present?
        #put the project into hash  
        hash[:project_id] = params[:project]
      end 
      #check if activity_type is present then  
      if params[:activity_type].present?
        #put the activity_type into hash
        hash[:activity_type_id] = params[:activity_type]
      end
      #check if from date is present then 
      if params[:from].present?
        hash[:employee_id] = current_user.employee_id
        hash[:status] = params[:status]
        #also check if from date is less than or equal to to date then
        if from.to_date <= to.to_date
          #put the from date to to date into hash
          hash[:date] = (from.to_date)..(to.to_date)
        #else check if from date is greater than to to date then  
        else from.to_date > to.to_date
          #put the to date to from date into hash
          hash[:date] = (to.to_date)..(from.to_date) 
        end 
      end 
      #find the record based on the hash attributes
      @record_froms = Tasksheet.where(hash).sort_by(&:date).sort_by(&:employee_id)
      #@record_froms.sort_by(&:date)
      #find the project based on the client id
      @projects  = Project.where(client_id: "#{params[:client]}").collect{ |u| [u.name, u.id] }
    end 
  end
   
  #show the project list based on the client 
  def project_for_client
    #if params[:client] is blank string then
    if params[:client] != ""
      #find the project based on the client id
      @projects = Project.where(client_id: "#{params[:client]}").collect{ |u| [u.name, u.id] }
    #else  
    else
      #find all projects 
      @projects = Project.getproject.collect{ |u| [u.name, u.id] } 
    end  
  end
 
  def edit
    #find the client from the Model: Client where id of the client is equal id in the params and assign it to variable “@client”
    @record = Tasksheet.where(id: params[:id]).first
    #if @client is blank
    if @record.blank?
      #return and redirect to clients list page with an error message
      return redirect_to reports_path, error: "Specified report is not found"
    end
  end
 
  #update the existing data
  def update
    #find the activity type from the Model: ActivityType where id of the activity type is equal id in the params and assign it to variable “@activity_type”
    @record = Tasksheet.where(id: params[:id]).first
    #if @activity_type is blank
    if @record.blank?
      #redirect to Activity Type list page with an error message
      return redirect_to reports_path, error: "Specified Record is not found"
    end
    #call skip_method variable by @record and put true in it
    @record.skip_method = true
    #concate of year, month and day into single date
    date = params[:date]["year"] +'/'+params[:date]["month"] +'/'+ params[:date]["day"]
    #concatenate of hour and minute into single time
    in_time = params[:in_time]["hour"] +':'+ params[:in_time]["minute"] 
    #concatenate of hour and minute into single time
    out_time = params[:out_time]["hour"] +':'+ params[:out_time]["minute"]
    #define a hash
    hash = {}
    #put the client into hash
    hash[:client_id] = params[:client]
    #put the project into hash  
    hash[:project_id] = params[:project]
    #put the activity_type into hash
    hash[:activity_type_id] = params[:activity_type]
    #put the task into hash 
    hash[:task] = params[:task]
    #put the date into hash 
    hash[:date] = date
    #put the in_time into hash 
    hash[:in_time] = in_time
    #put the out_time into hash 
    hash[:out_time] = out_time
    #put the remark into hash 
    hash[:remark] = params[:remark]
    #if update is saved successfully 
    if @record.update_attributes(hash)
      #redirect to "reports index" page with success message
      return redirect_to reports_path, notice: "Record updated successfully"
    #else  
    else
      #return and render the action "edit"
      return render action: "edit"
    end
  end
  
  def submit_for_approval 
    #debugger
    obj = params[:my_param].split
    hash = {}
    hash[:employee_id] = params[:ids]
    if obj.length > 1
      hash[:date] = (obj[0].to_date)..(obj[1].to_date)
    else
      hash[:date] = obj
    end 
    #debugger
    if params[:status] == "reject"
      hash[:status] = "reject"
    else 
      hash[:status] = "new" 
    end 
    #debugger  
    #hash[:employee_id] = current_user.employee_id  
    #date_arr = Array.class_eval(params[:my_param])
    
    #debugger
    #hash[:date] = (date_arr[0].to_date)..(date_arr[1].to_date)
    #hash[:
    #@task = Tasksheet.where(date: params[:my_param])
    Tasksheet.where(hash).update_all(status: "submit", reason: "")    
  end
  
  def all_submit
    if Tasksheet.where(employee_id: current_user.employee_id, status: "#{params[:status]}", date: ("#{params[:dates].first}".."#{params[:dates].last}")).update_all(status: "submit")
      redirect_to reports_path, notice: "Record has been submitted successfully"
    else
      redirect_to reports_path, notice: "Record not submitted"
    end 
  end
   
  #####################
  ## Protected Methods
  #####################
  protected

  ###################
  ## Private Methods
  ###################
  private

end               

app/views/reports/_data_record.html.erb
<tr id="row_id_<%= data_record.date %>">
  <td>
    <%= data_record.client.name %>
  </td>
  <td>
    <%= data_record.project.name %>
  </td>
  <td>
    <%= data_record.activity_type.name %>
  </td>
  <td>
    <%= data_record.task %>
  </td>
  <td>
    <%= data_record.date %>
  </td>
  <td>
    <%= data_record.in_time.strftime("%H:%M") %>
  </td>
  <td>
    <%= data_record.out_time.strftime("%H:%M") %>
  </td> 
  <td>
    <%= data_record.remark %>
  </td>
  <% if (data_record.status == "new" || data_record.status == "reject") %>
    <td class = "link_hide_<%= data_record.date %>">
      <%= link_to "Edit", edit_report_path(data_record.id)   %>
      <%= link_to "Delete", data_record, method: :delete, confirm: 'Are you sure?' %>
    </td> 
  <% end %>      
</tr>

app/views/reports/_form.html.erb
<%= form_tag(report_path, method: :put) do  %> 
  <div>
    <table class="imagetable">
      <tr>
        <td><%= @record.client.name %></td>
        <td><%= @record.project.name %></td>
        <td><%= @record.activity_type.name %></td>
        <td><%= @record.task %></td>
        <td><%= @record.date %></td>
        <td><%= @record.in_time.strftime("%H:%M") %></td>
        <td><%= @record.out_time.strftime("%H:%M") %></td> 
      </tr>
      <tr>
        <td colspan="7">
        <%= submit_tag "Update" %>
        </td>
      </tr>
    </table>
  </div>
<% end %>  

app/views/reports/_report.html.erb
<tr id="row">
  <td>
    <%= select_tag "status", options_for_select([['new'], ['submit'], ['accept'], ['reject']], selected: params[:status]), style: "width: 165px;" %> 
  </td>
  <td>
    <%= select_tag "client", options_for_select(Client.getclient.collect{ |u| [u.name, u.id] }, selected: params[:client].to_i), prompt: "Show all",
        data: {
          remote: true,
          url: url_for(action: :project_for_client)
        }, style: "width:165px;" %>                                 
  </td>
  <td>
    <% if !params[:client].present? %>
      <%= select_tag "project", options_for_select(Project.getproject.collect{ |u| [u.name, u.id] }, selected: params[:project].to_i), prompt: "Show all", style: "width:165px;" %> 
    <% else %>
      <%= select_tag "project", options_for_select(@projects, selected: params[:project].to_i), prompt: "Show all", style: "width:165px;" %>   
    <% end %>  
  </td>
  <td>
    <%= select_tag "activity_type", options_for_select(ActivityType.getactivity_type.collect{ |u| [u.name, u.id] }, selected: params[:activity_type].to_i) , prompt: "Show all", style: "width: 165px;" %> 
  </td>
  <td>
    <% if !params[:from].present? %>
      <%= select_date Date.today, prefix: "from" %>
    <% else %>
    <% from = params[:from]["year"] +'/'+params[:from]["month"] +'/'+ params[:from]["day"] %>
      <%= select_date from.to_date, prefix: "from" %>
    <% end %>     
  </td>
  <td>
    <% if !params[:to].present? %>
      <%= select_date Date.today, prefix: "to" %>
    <% else %>
    <% to = params[:to]["year"] +'/'+params[:to]["month"] +'/'+ params[:to]["day"] %>
      <%= select_date to.to_date, prefix: "to" %>
    <% end %> 
  </td>
</tr>
  

app/views/reports/_report_edit.html.erb
<tr>
  <td>
    <%= select_tag "client", options_for_select(Client.getclient.collect{ |u| [u.name, u.id] }, selected: @record.client_id), prompt: "Select Client",
          data: {
            remote: true,
            url: url_for(action: :project_for_client)
          }, style: "width:165px;" %> 
    <% if @record.errors.present? && @record.errors[:client].present? %>
      <%= @record.errors[:client].join(", ") %>
    <% end %>                      
  </td>
  <td>
    <% if @record.client_id  %>
      <%= select_tag "project", options_for_select(Project.where(client_id: @record.client_id).collect{ |u| [u.name, u.id] }, selected: @record.project_id), prompt: "select project", style: "width:165px;" %> 
      <% if @record.errors.present? && @record.errors[:project].present? %>
      <%= @record.errors[:project].join(", ") %>
      <% end %> 
    <% else %>
      <%= select_tag "project", "[]", prompt: "Select PROJECT", style: "width:165px;" %>
    <% end %> 
  </td>
  <td>
    <%= select_tag "activity_type", options_for_select(ActivityType.getactivity_type.collect{ |u| [u.name, u.id] }, selected: @record.activity_type_id), prompt: "Select Activity Type", style: "width: 165px;" %> 
    <% if @record.errors.present? && @record.errors[:activity_type].present? %>
      <%= @record.errors[:activity_type].join(", ") %>
    <% end %>
  </td>
  <td>
    <%= text_field_tag "task", @record.task %>
    <% if @record.errors.present? && @record.errors[:task].present? %>
      <%= @record.errors[:task].join(", ") %>
    <% end %>
  </td>
  <td>
    <% if @record.date != nil %>
      <%= select_date @record.date, prefix: "date" %>
    <% else %>
      <%= select_date Date.today, prefix: "date" %>
    <% end %>  
    <% if @record.errors.present? && @record.errors[:date].present? %>
      <%= @record.errors[:date].join(", ") %>
    <% end %>
  </td>
  <td>
    <%= select_time @record.in_time, prefix: "in_time", minute_step: 15 %>
    <% if @record.errors.present? && @record.errors[:in_time].present? %>
      <%= @record.errors[:in_time].join(", ") %>
    <% end %>
  </td>
  <td>
    <%= select_time @record.out_time, prefix: "out_time", minute_step: 15 %> 
    <% if @record.errors.present? && @record.errors[:out_time].present? %>
      <%= @record.errors[:out_time].join(", ") %>
    <% end %>    
  </td>
  <td>
    <%= text_field_tag "remark", @record.remark %>
  </td>
</tr>
  

app/views/reports/edit.html.erb
<h1> Edit the record </h1>
<%= form_tag(report_path, method: :put) do  %> 
  <table id = "record" class = "imagetable">
    <tr>
      <th align = "left"> Client </th>
      <th align = "left"> Project </th>
      <th align = "left"> Activity Type </th>
      <th align = "left"> Task </th>
      <th align = "left"> Date </th> 
      <th align = "left"> In Time </th>
      <th align = "left"> Out Time </th>
      <th align = "left"> Remark </th>
    </tr> 
      <%= render partial: "reports/report_edit" %>
    <tr>
      <td align = "center" colspan="8"><%= submit_tag "Update" %></td>
    </tr> 
  </table>
<% end %>
<%= link_to("Back", reports_path) %>

app/views/reports/index.html.erb
 <h1> Reports </h1>
<%= form_tag(reports_path, method: :get) do  %> 
  <table id = "record" class = "imagetable">
    <tr>
      <th align = "left"> Status </th>
      <th align = "left"> Client </th>
      <th align = "left"> Projects </th>
      <th align = "left"> Activity Type </th>
      <th align = "left"> From </th>
      <th align = "left"> To </th>
    </tr> 
    <%= render partial: "reports/report" %>
    <tr>  
      <td colspan="10", align = "center"><%= submit_tag "Find" %></td>
    </tr> 
    <% if params[:from].present? %>
      <% if @record_froms.present? %>
        <tr>
          <th align = "left"> Client </th>
          <th align = "left"> Project </th>
          <th align = "left"> Activity Type </th>
          <th align = "left"> Task </th>
          <th align = "left"> Date </th> 
          <th align = "left"> In Time </th>
          <th align = "left"> Out Time </th>
          <th align = "left"> Remark </th>
          <th colspan="2", align = "left"> Action </th>
        </tr>
        <% date_arr = [] %>
        <% @record_froms.each do |record| %>
          <% date_arr << record.date %>
        <% end %>  
        <% date_arr = date_arr.uniq %> 
        <% date_arr.each do |date| %>
          <% @record = [] %>
          <% @record_froms.each do |record| %>
            <% if date == record.date %>
              <% @record << record %>
            <% end %>  
          <% end %>
          <% @record = @record.sort_by(&:in_time) %>
          <%= render partial: "reports/data_record", collection: @record %> 
          <tr> 
            <td id= "link_id_<%= "#{@record[0].date}" %>" colspan="10" align = "center">
              <% if (@record[0].status == "new" || @record[0].status == "reject") %> 
                <% if @record[0].status == "reject" %>
                  <h4><%= "this tasksheet has been rejected because the reason is ->" %>
                      <b><font color="red"><%= @record[0].reason %></font></b>
                  </h4> 
                  <%= link_to "Submit Again :)", "#", onclick: "submit_for_approval('#{date}', '#{current_user.employee_id}', '#{params[:status]}');return false;" %>
                <% else %>             
                  <%= link_to "Submit for approval for date #{@record[0].date}", "#", onclick: "submit_for_approval('#{date}', '#{current_user.employee_id}', '#{params[:status]}');return false;" %> 
                <% end %>  
              <% end %>    
            </td>
          </tr> 
        <% end %> 
        <tr> 
          <% from = params[:from]["year"] +'/'+params[:from]["month"] +'/'+ params[:from]["day"] %>
          <% to = params[:to]["year"] +'/'+params[:to]["month"] +'/'+ params[:to]["day"] %>
          <td id = "link" colspan="10", align = "left">
          <% flag = false %> 
          <% @record_froms.each do |record| %>
            <% if (record.status == "new" || record.status == "reject") %>
              <% flag = true %>
            <% end %>
          <% end %>  
          <% if flag == true %> 
            <% @arr = [] %>
            <% @arr << from %>
            <% @arr << to %>
              <%= link_to "All submit for approval from date #{from} to #{to}", all_submit_path(:dates => @arr,:status => "#{params[:status]}" ), method: :post%> 
          <% else %>
            <%= "All submitted" %>
          <% end %> 
          </td>
        </tr>  
      <% else %>
        <tr><td colspan="8"> "No Record found" </td></tr>
      <% end %>
    <% end %>  
  </table> 
<% end %>

app/views/reports/project_for_client.js.erb
<% if params[:client] != "" %>
  $("#project").html(" <%=j select_tag("project", options_for_select(@projects), prompt: "Show all") %> ");
<% else %>
  $("#project").html(" <%=j select_tag("project", options_for_select(@projects), prompt: "Show all") %> ");
<% end %>  

app/views/reports/submit_for_approval.js.erb
<%# debugger %> 
 
$("#link_id_<%= "#{params[:my_param]}" %>").html("submitted");
$(".link_hide_<%= "#{params[:my_param]}" %>").hide(); 
 

 