config/routes.rb
TimesheetManagement::Application.routes.draw do

  authenticated :user do
    root :to => 'home#index', :as => :authenticated_root
  end
   
  devise_for :users, :controllers => {:confirmations => 'confirmations'}, :skip => [:sessions]
  devise_scope :user do 
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    post 'login' => 'devise/sessions#create', :as => :user_session
    delete 'login' => 'devise/sessions#destroy', :as => :destroy_user_session
    get 'forgot-password' => 'devise/passwords#new', :as => :new_user_password
    get 'confirmation-instruction' => 'confirmations#new', :as => :new_user_confirmation
    put "/confirm" => "confirmations#confirm"
  end
  
  devise_scope :user do 
    put "/confirm" => "confirmations#confirm"
  end
  
  resources :employees, except: ["show"]
  resources :clients
  resources :projects, except: ["show"]
  resources :activity_types, except: ["show"]
  resources :tasksheets 
  get "/projects_for_client" => "tasksheets#projects_for_client"
  
  post "tasksheets/create_row" => "tasksheets#create_row", as: "create_row"

  resources :reports 
  get "/project_for_client" => "reports#project_for_client"
  post "reports/submit_for_approval" => "reports#submit_for_approval", as: "submit_for_approval"
  post "reports/all_submit" => "reports#all_submit", as: "all_submit"
  
  resources :check_reports
  get "/project_for_client_admin" => "check_reports#project_for_client_admin"
  post "check_reports/accept_data" => "check_reports#accept_data", as: "accept_data"
  post "check_reports/reject_data" => "check_reports#reject_data", as: "reject_data"
  post "check_reports/reason_for_rejection" => "check_reports#reason_for_rejection", as: "reason_for_rejection"
  post "check_reports/accept_all_data" => "check_reports#accept_all_data", as: "accept_all_data"
  post "check_reports/reject_all_data" => "check_reports#reject_all_data", as: "reject_all_data"
  

   root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timesheet Management</title>
    <%= stylesheet_link_tag :application, media: "all" %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tags %>
  </head>
  <body class = "body">
    <p class = "notice"><%= notice %></p>
    <p class = "alert"><%= alert %></p>
    <% if user_signed_in? %>
      <div class = "logout">
        <%= link_to 'Change password', edit_user_registration_path %>
        <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %> 
      </div></br>
      <div>
      <table>
        <% if current_user.name == "admin" %>
          <th>
            <td><h3><%= link_to "Clients Management", clients_path %></h3></td>
            <td><h3><%= link_to "Activity Types Management", activity_types_path %></h3></td>
            <td><h3><%= link_to "Projects Management", projects_path %></h3></td> 
            <td><h3><%= link_to "Employees Management", employees_path %></h3></td>
            <td><h3><%= link_to "Tasksheet Module", tasksheets_path %></h3></td>
            <td><h3><%= link_to "Check Reports", check_reports_path %></h3></td>
          </th> 
        <% else %>
          <td><h3><%= link_to "Tasksheet Module", tasksheets_path %>&nbsp;&nbsp;&nbsp;</h3></td> 
          <td><h3><%= link_to "Reports", reports_path %>&nbsp;&nbsp;&nbsp;</h3></td>
        <% end %>  
      </table> 
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>